# Generated by Django 4.2.2 on 2023-08-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1500)),
                ('request_id', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=500)),
                ('apt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=50)),
                ('zip_code', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('solicitud_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('agency_responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['request_id'],
            },
        ),
        migrations.CreateModel(
            name='tiposolicitud',
            fields=[
                ('idtipoSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoSolicitud', models.CharField(blank=True, max_length=250, verbose_name='Nombre del tipo de solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500, null=True)),
                ('street_address', models.CharField(max_length=500)),
                ('bld_number', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='México', max_length=50)),
                ('zip_code', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('solicitud_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='abierto', max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('agency_responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguimiento_ciudadano.tiposolicitud')),
            ],
            options={
                'ordering': ['request_id'],
            },
        ),
    ]
