# Generated by Django 4.2.2 on 2023-08-21 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_api',
            name='solicitud_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
