# Generated by Django 4.2.4 on 2023-08-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0002_solicitudes_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='autor',
        ),
    ]
