# Generated by Django 4.2.2 on 2023-08-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0002_solicitudes_updated_at_alter_solicitudes_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='apt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='country',
            field=models.CharField(default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
