# Generated by Django 4.2.2 on 2023-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0003_alter_solicitudes_apt_number_alter_solicitudes_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
