# Generated by Django 4.2.2 on 2023-08-21 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0003_alter_solicitudes_solicitud_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitud_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
