# Generated by Django 4.2.4 on 2023-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0003_remove_solicitudes_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
