# Generated by Django 4.2.2 on 2023-08-21 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0004_alter_solicitudes_solicitud_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitud_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudes_api',
            name='solicitud_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
