# Generated by Django 4.2.2 on 2023-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0004_alter_solicitudes_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
