# Generated by Django 4.2.2 on 2023-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0005_alter_solicitudes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
