# Generated by Django 4.2.2 on 2023-08-21 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0005_alter_solicitudes_solicitud_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitud_datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='solicitudes_api',
            name='solicitud_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True),
        ),
    ]
