# Generated by Django 4.2.2 on 2023-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_ciudadano', '0006_alter_solicitudes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='long',
            field=models.FloatField(),
        ),
    ]
